### ISSUE TITLE
Evolución Incendio

### ISSUE THREAD

**Issue by miguelanguai** [miguelanguai/FireSpotter#30]
Generar una estela del incendio en la última semana (los incendios que aun esten activos)

**Comment by pablocru** [comment]
Tal como he comentado en la Issue #31, esta aplicacion es solo frontend y no tiene una base de datos. Las funcionalidades que tengan que ver con uso de base de datos no se pueden implementar por ahora.

Vuelvo a proponer el uso de "local storage" o "session storage", pero este historico variara entre navegadores y usuarios.
