### ISSUE TITLE
Histórico incendios en la BBDD

### ISSUE THREAD

**Issue by miguelanguai** [miguelanguai/FireSpotter#31]
Con puntos de colores, podemos dejar apuntado donde han existido incendios que nosotros tenemos guardados. Eso lo podemos hacer con otra capa diferente del mapa

**Comment by pablocru** [comment]
No hay base de datos. Todo se obtiene de APIs publicas y no se almacenan los resultados. Cuando se cierra la app se pierden los registros.

Una alternativa seria usar "local storage" o "session storage" para almacenar las consultas que el usuario ha realizado. Pero solo se guardan aquellas que se hagan en el mismo navegador.

**Comment by adgarrod** [comment]
Si hacemos eso, es facil que sobre saturemos la app por no tener servidores, imagina que tenga que plotear todos los incendios de Funchal que han habido estos dias, mas los incendios y puntos calientes que se detecten. Ademas de hacer distincion entre ellos.

**Comment by pablocru** [comment]
Otra opción es que solo se rendericen fuegos por continente y bloquear el desplazamiento del mapa al continente seleccionado. Seguro que la API del mapa tiene que tener la funcionalidad de sacar, por ejemplo, solo Europa. ¿Alguien puede verificar eso? Si esta, lo implementamos con prioridad.
