### ISSUE TITLE
Selección servidor origen de información 

### ISSUE THREAD

**Issue by miguelanguai** [miguelanguai/FireSpotter#32]
Podemos poner en un formulario el servidor del cual sacamos la información. Creo que ya está hecho, pero por apuntarlo

**Comment by pablocru** [comment]
En lugar de un formulario, seria mas adecuado usar un desplegable que muestre los satelites del FIRMS que hemos testeado que dan informacion relevante y poder cambiar a tiempo real entre uno y otro (Issue #21).
