### ISSUE TITLE
Incendios mas cercanos al usuario

### ISSUE THREAD

**Issue by miguelanguai** [miguelanguai/FireSpotter#34]
Como las APIS solo nos dejan sacar información limitada sobre incendios, hacer que esta sea de los incendios mas cercanos al usuario en coordenadas

**Comment by pablocru** [comment]
Me parece muy buena idea pintar aquellos puntos cercanos al area del usuario. Asi se evita sobrecargar la app. Si el usuario no tiene la localizacion habilitada o no da permisos, que se muestre un area aproximada de España, tal y como esta ahora.

**Comment by adgarrod** [comment]
Tambien digo, no tiene mucho sentido, por que imaginate que en España no hay incendios y el mas cercano esta en Portugal¿?
No tiene sentido
